title: Abhi Jadhav
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Abhi Jadhav
baseurl: "" # the subpath of your site, e.g. /blog/

# the base hostname & protocol for your site
url: "http://a1pha.github.io/"

port: 8080 # Gets overwritten by github. Need this for testing purposes

exclude: [Gemfile, Gemfile.lock]

google_analytics_id: UA-185753767-1

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
